// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzKf2uGgjdxDMOMwkigmxczQU8RQLWgE',
    appId: '1:213940967151:web:530f3e6d1ebcdb729fad1a',
    messagingSenderId: '213940967151',
    projectId: 'momentum-51138',
    authDomain: 'momentum-51138.firebaseapp.com',
    storageBucket: 'momentum-51138.firebasestorage.app',
    measurementId: 'G-51MHXW7119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWZMOZyT3AeaDIXFiBP71aEfx6ICg7cb8',
    appId: '1:213940967151:android:295cca094492b24f9fad1a',
    messagingSenderId: '213940967151',
    projectId: 'momentum-51138',
    storageBucket: 'momentum-51138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_gZKG3b8SB8XIx4VX1heg5MecXRRw2k',
    appId: '1:213940967151:ios:1d017d59275e45199fad1a',
    messagingSenderId: '213940967151',
    projectId: 'momentum-51138',
    storageBucket: 'momentum-51138.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU_gZKG3b8SB8XIx4VX1heg5MecXRRw2k',
    appId: '1:213940967151:ios:1d017d59275e45199fad1a',
    messagingSenderId: '213940967151',
    projectId: 'momentum-51138',
    storageBucket: 'momentum-51138.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzKf2uGgjdxDMOMwkigmxczQU8RQLWgE',
    appId: '1:213940967151:web:7ecc1191381cdbbe9fad1a',
    messagingSenderId: '213940967151',
    projectId: 'momentum-51138',
    authDomain: 'momentum-51138.firebaseapp.com',
    storageBucket: 'momentum-51138.firebasestorage.app',
    measurementId: 'G-KX8THZ68JE',
  );
}
